#!/bin/bash

cd src
rm *.class
rm *_Stub.java

javac RMISSLClientSocketFactory.java
javac RMISSLServerSocketFactory.java
javac myIRCObject.java
javac myIRCCallbackImpl.java
rmic -keep myIRCObject
javac myIRCServer.java
javac myIRC.java