/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPSPEC_H_RPCGEN
#define _RPSPEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct file_part {
  char *chunck;
  uint32_t last;
};
typedef struct file_part file_part;

struct file_desc {
  char *filename;
  uint32_t offset;
};
typedef struct file_desc file_desc;

#define PROG 0x12345688
#define VERS 1

#define PSIZE 1024

#if defined(__STDC__) || defined(__cplusplus)
#define RPWD 1
extern  char ** rpwd_1(void *, CLIENT *);
extern  char ** rpwd_1_svc(void *, struct svc_req *);
#define RCD 2
extern  int32_t * rcd_1(char **, CLIENT *);
extern  int32_t * rcd_1_svc(char **, struct svc_req *);
#define RLS 3
extern  char ** rls_1(void *, CLIENT *);
extern  char ** rls_1_svc(void *, struct svc_req *);
#define RGET 4
extern  file_part * rget_1(char **, CLIENT *);
extern  file_part * rget_1_svc(char **, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPWD 1
extern  char ** rpwd_1();
extern  char ** rpwd_1_svc();
#define RCD 2
extern  int32_t * rcd_1();
extern  int32_t * rcd_1_svc();
#define RLS 3
extern  char ** rls_1();
extern  char ** rls_1_svc();
#define RGET 4
extern  file_part * rget_1();
extern  file_part * rget_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_part (XDR *, file_part*);
extern  bool_t xdr_file_desc (XDR *, file_desc*);

#else /* K&R C */
extern bool_t xdr_file_part ();
extern bool_t xdr_file_desc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPSPEC_H_RPCGEN */