/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPSPEC_H_RPCGEN
#define _RPSPEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arga {
	int arga1;
	int arga2;
};
typedef struct arga arga;

#define PROG 0x12345678
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPROCA 1
extern  double * rproca_1(arga *, CLIENT *);
extern  double * rproca_1_svc(arga *, struct svc_req *);
#define RPROCB 2
extern  arga * rprocb_1(void *, CLIENT *);
extern  arga * rprocb_1_svc(void *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPROCA 1
extern  double * rproca_1();
extern  double * rproca_1_svc();
#define RPROCB 2
extern  arga * rprocb_1();
extern  arga * rprocb_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arga (XDR *, arga*);

#else /* K&R C */
extern bool_t xdr_arga ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPSPEC_H_RPCGEN */
